ALTER TABLE robots
    ADD COLUMN IF NOT EXISTS position_x DOUBLE PRECISION NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS position_y DOUBLE PRECISION NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS direction_degrees DOUBLE PRECISION NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS stop BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS target_position_x DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS target_position_y DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS set_velocity DOUBLE PRECISION NOT NULL DEFAULT 1,
    ADD COLUMN IF NOT EXISTS velocity DOUBLE PRECISION NOT NULL DEFAULT 0;

ALTER TABLE telemetry
    ADD COLUMN IF NOT EXISTS velocity_cm_s DOUBLE PRECISION NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS direction_degrees DOUBLE PRECISION NOT NULL DEFAULT 0;
