ALTER TABLE robots
    ADD COLUMN IF NOT EXISTS position_x DOUBLE PRECISION NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS position_y DOUBLE PRECISION NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS velocity_cm_s DOUBLE PRECISION NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS direction_degrees DOUBLE PRECISION NOT NULL DEFAULT 0;

ALTER TABLE telemetry
    ADD COLUMN IF NOT EXISTS velocity_cm_s DOUBLE PRECISION NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS direction_degrees DOUBLE PRECISION NOT NULL DEFAULT 0;
