global:
  resolve_timeout: 5m

route:
  receiver: backend-webhook
  group_wait: 10s
  group_interval: 1m
  repeat_interval: 1h

receivers:
  - name: backend-webhook
    webhook_configs:
      - url: http://backend:8089/internal/alertmanager/webhook
        send_resolved: true
